// <auto-generated />
using System;
using CNPM_Nhom12.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CNPM_Nhom12.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516012656_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CNPM_Nhom12.Models.BudgetLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("LimitAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("BudgetLimits");
                });

            modelBuilder.Entity("CNPM_Nhom12.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BgColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BgColor = "#FAEEDA",
                            Color = "#BA7517",
                            Icon = "ti ti-tools-kitchen-2",
                            Name = "Ăn uống",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            BgColor = "#FAEEDA",
                            Color = "#BA7517",
                            Icon = "ti ti-motorbike",
                            Name = "Di chuyển",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            BgColor = "#EEEDFE",
                            Color = "#534AB7",
                            Icon = "ti ti-device-tv",
                            Name = "Giải trí",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            BgColor = "#FCEBEB",
                            Color = "#993C1D",
                            Icon = "ti ti-plug",
                            Name = "Tiện ích",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            BgColor = "#E6F1FB",
                            Color = "#185FA5",
                            Icon = "ti ti-school",
                            Name = "Giáo dục",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            BgColor = "#E1F5EE",
                            Color = "#0F6E56",
                            Icon = "ti ti-cash",
                            Name = "Lương",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            BgColor = "#E1F5EE",
                            Color = "#0F6E56",
                            Icon = "ti ti-gift",
                            Name = "Thưởng",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            BgColor = "#E6F1FB",
                            Color = "#185FA5",
                            Icon = "ti ti-coins",
                            Name = "Đầu tư",
                            Type = 0
                        });
                });

            modelBuilder.Entity("CNPM_Nhom12.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CNPM_Nhom12.Models.BudgetLimit", b =>
                {
                    b.HasOne("CNPM_Nhom12.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CNPM_Nhom12.Models.Transaction", b =>
                {
                    b.HasOne("CNPM_Nhom12.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CNPM_Nhom12.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
